function updatePathISBI()

addpath(...
     '/home/thanujaa/projects/contourDetection', ...
     '/home/thanujaa/projects/contourDetection/RF', ...
     '/home/thanujaa/projects/contourDetection/createTrainingData', ...
     '/home/thanujaa/projects/common/imgNormalization', ...
     '/home/thanujaa/projects/matlabprojects/bmrm', ...
     '/home/thanujaa/projects/common', ...
     '/home/thanujaa/projects/external/imageprocessing/GCMex', ...
     '/home/thanujaa/projects/sectionThickness', ...
     '/home/thanujaa/projects/common/stats', ...
     '/home/thanujaa/projects/common/3Dstacks', ...
     '/home/thanujaa/projects/common/file_dir_ops', ...
     '/home/thanujaa/projects/common/rescaling', ...
     '/home/thanujaa/projects/common/visualization', ...
     '/home/thanujaa/projects/common/visualization/shadedErrorBar', ...
     '/home/thanujaa/projects/external/saveastiff_2.51', ...
     '/home/thanujaa/projects/external/normxcorr2_mex_ALL/cv_src', ...
     '/home/thanujaa/projects/external/normxcorr2_mex_ALL', ...
     '/home/thanujaa/projects/classifiers/matlabClassificationCommon', ...
     '/home/thanujaa/projects/matlabprojects/sift', ...
     '/home/thanujaa/projects/matlabprojects/membrane_RF/membraneDetection', ...
     '/home/thanujaa/programs/gurobi603/linux64/matlab', ...
     '/home/thanujaa/projects/matlabprojects/randomforest-matlab/RF_Reg_C', ...
     '/home/thanujaa/projects/matlabprojects/randomforest-matlab/RF_Class_C', ...
     '/home/thanujaa/projects/matlabprojects/eval_NIPS2013_2/NIPS2013', ...
     '/home/thanujaa/projects/matlabprojects/progressbar', ...
     '/home/thanujaa/projects/matlabprojects/orientations', ...
     )

