function updatePathISBI()

addpath(...
     '/home/thanujaa/projects/contourdetection', ...
     '/home/thanujaa/projects/contourdetection/RF', ...
     '/home/thanujaa/projects/contourdetection/createTrainingData', ...
     '/home/thanujaa/projects/common/imgNormalization', ...
     '/home/thanujaa/projects/matlabprojects/bmrm', ...
     '/home/thanujaa/projects/common', ...
     '/home/thanujaa/projects/common/stats', ...
     '/home/thanujaa/projects/common/3Dstacks', ...
     '/home/thanujaa/projects/common/file_dir_ops', ...
     '/home/thanujaa/projects/common/rescaling', ...
     '/home/thanujaa/projects/common/visualization', ...
     '/home/thanujaa/projects/common/visualization/shadedErrorBar', ...
     '/home/thanujaa/projects/matlabprojects/sift', ...
     '/home/thanujaa/projects/matlabprojects/membrane_RF/membraneDetection', ...
     '/usr/pack/gurobi-6.5.1-sa/gurobi651/linux64/matlab', ...
     '/home/thanujaa/projects/matlabprojects/randomforest-matlab/RF_Reg_C', ...
     '/home/thanujaa/projects/matlabprojects/randomforest-matlab/RF_Class_C', ...
     '/home/thanujaa/projects/matlabprojects/eval_NIPS2013_2/NIPS2013', ...
     '/home/thanujaa/projects/matlabprojects/progressbar', ...
     '/home/thanujaa/projects/matlabprojects/orientations');
