function updatePathISBI()

p = [...
%%% BEGIN ENTRIES %%%
     '/home/thanuja/projects/contourDetection:', ...
     '/home/thanuja/projects/contourDetection/RF:', ...
     '/home/thanuja/projects/contourDetection/createTrainingData:', ...
     '/home/thanuja/projects/common/imgNormalization:', ...
     '/home/thanuja/projects/matlabprojects/bmrm:', ...
     '/home/thanuja/projects/common:', ...
     '/home/thanuja/projects/external/imageprocessing/GCMex:', ...
     '/home/thanuja/projects/sectionThickness:', ...
     '/home/thanuja/projects/common/stats:', ...
     '/home/thanuja/projects/common/3Dstacks:', ...
     '/home/thanuja/projects/common/file_dir_ops:', ...
     '/home/thanuja/projects/common/rescaling:', ...
     '/home/thanuja/projects/common/visualization:', ...
     '/home/thanuja/projects/common/visualization/shadedErrorBar:', ...
     '/home/thanuja/projects/external/saveastiff_2.51:', ...
     '/home/thanuja/projects/external/normxcorr2_mex_ALL/cv_src:', ...
     '/home/thanuja/projects/external/normxcorr2_mex_ALL:', ...
     '/home/thanuja/projects/classifiers/matlabClassificationCommon:', ...
     '/home/thanuja/projects/matlabprojects/sift:', ...
     '/home/thanuja/projects/matlabprojects/membrane_RF/membraneDetection:', ...
     '/home/thanuja/programs/gurobi603/linux64/matlab:', ...
     '/home/thanuja/projects/matlabprojects/randomforest-matlab/RF_Reg_C:', ...
     '/home/thanuja/projects/matlabprojects/randomforest-matlab/RF_Class_C:', ...
     '/home/thanuja/projects/matlabprojects/eval_NIPS2013_2/NIPS2013:', ...
     '/home/thanuja/projects/matlabprojects/progressbar:', ...
     '/home/thanuja/projects/matlabprojects/orientations:', ...
     ];

addpath(p)