function overlappingSlices = getOverlappingSlices(...
            slicesAll,slicesPerSection,searchRadius)
        
overlappingSlices = struct(...
        'sectionID',0,...
        'sliceID',0,...
        'pixelInds',cc.PixelIdxList);